apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: escriptpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: amoghlokhande/escriptpro-authservice
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: escriptpro
spec:
  selector:
    app: authservice
  ports:
    - port: 8080