apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: escriptpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      initContainers:
      - name: wait-for-postgres
        image: alpine:3.19
        command:
          - sh
          - -c
          - |
            apk add --no-cache bind-tools netcat-openbsd
            until nslookup postgres; do sleep 2; done;
            until nc -z postgres 5432; do sleep 2; done;

      containers:
      - name: doctor-service
        image: amoghlokhande/doctor-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        envFrom:
        - secretRef:
            name: s3-config

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: escriptpro
spec:
  selector:
    app: doctor-service
  ports:
    - port: 8086
      targetPort: 8086