apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: escriptpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
      - name: doctor-service
        image: amoghlokhande/escriptpro-doctor-service
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: escriptpro
spec:
  selector:
    app: doctor-service
  ports:
    - port: 8086