apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicine-service
  namespace: escriptpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicine-service
  template:
    metadata:
      labels:
        app: medicine-service
    spec:
      initContainers:
      - name: wait-for-postgres
        image: alpine:3.19
        command:
          - sh
          - -c
          - |
            apk add --no-cache bind-tools netcat-openbsd
            until nslookup postgres; do sleep 2; done;
            until nc -z postgres 5432; do sleep 2; done;

      containers:
      - name: medicine-service
        image: amoghlokhande/escriptpro-medicine-service
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: medicine-service
  namespace: escriptpro
spec:
  selector:
    app: medicine-service
  ports:
    - port: 8084
      targetPort: 8084