apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: escriptpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: amoghlokhande/escriptpro-patient-service
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: escriptpro
spec:
  selector:
    app: patient-service
  ports:
    - port: 8082
      targetPort: 8082