apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-service
  namespace: escriptpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-service
  template:
    metadata:
      labels:
        app: pdf-service
    spec:
      containers:
      - name: pdf-service
        image: amoghlokhande/escriptpro-pdf-service
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-service
  namespace: escriptpro
spec:
  selector:
    app: pdf-service
  ports:
    - port: 8085
      targetPort: 8085